// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEqZoqYtPLgcGb0928hv-6xAsOvsMCSs',
    appId: '1:444841214901:web:5e7751509f47962d9f8ffc',
    messagingSenderId: '444841214901',
    projectId: 'teabotflutter',
    authDomain: 'teabotflutter.firebaseapp.com',
    storageBucket: 'teabotflutter.firebasestorage.app',
    measurementId: 'G-7YRKFYR65E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcFZDX4BIh25CjcDiZT8_y57FH9Ex3yzM',
    appId: '1:444841214901:android:ec399369c8b77a449f8ffc',
    messagingSenderId: '444841214901',
    projectId: 'teabotflutter',
    storageBucket: 'teabotflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDacsMECdbcff9QBKLQcDowlwUZ8XE4GFU',
    appId: '1:444841214901:ios:89041a5b881c26aa9f8ffc',
    messagingSenderId: '444841214901',
    projectId: 'teabotflutter',
    storageBucket: 'teabotflutter.firebasestorage.app',
    iosBundleId: 'com.example.teabot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDacsMECdbcff9QBKLQcDowlwUZ8XE4GFU',
    appId: '1:444841214901:ios:89041a5b881c26aa9f8ffc',
    messagingSenderId: '444841214901',
    projectId: 'teabotflutter',
    storageBucket: 'teabotflutter.firebasestorage.app',
    iosBundleId: 'com.example.teabot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtubFChkfaRwNKBCzFfUJZg_QClupZrrI',
    appId: '1:444841214901:web:8df8e97e7cd3cc7f9f8ffc',
    messagingSenderId: '444841214901',
    projectId: 'teabotflutter',
    authDomain: 'teabotflutter.firebaseapp.com',
    storageBucket: 'teabotflutter.firebasestorage.app',
    measurementId: 'G-SS5HL9C9EK',
  );
}
